### PR TITLE
Fixes #138 #158. Pull image before building image

### LINKED ISSUE #138: Try PULL image more then one if service response HTTP 505
If the docker registry returns HTTP 503, I would prefer to run docker pull once more.
Sometimes, a second run works properly.

What do you think? @pkubatrh @hhorak @praiskup.

See the error:
```
make[1]: Entering directory `/tmp/daily_scl_tests/s2i-nodejs-container'
mkdir -p 10/root
go-md2man -in "10/README.md" -out "10/root/help.1"
chmod a+r "10/root/help.1"
VERSION="10" SKIP_SQUASH=1 UPDATE_BASE= OS=fedora CLEAN_AFTER= DOCKER_BUILD_CONTEXT=. OPENSHIFT_NAMESPACES="" CUSTOM_REPO="" /usr/bin/env bash common/build.sh
-> Version 10: building image from 'Dockerfile.fedora' ...
Sending build context to Docker daemon 50.69 kB

Step 1/13 : FROM registry.fedoraproject.org/f29/s2i-base:latest
Trying to pull repository registry.fedoraproject.org/f29/s2i-base ... 
latest: Pulling from registry.fedoraproject.org/f29/s2i-base
7692efc5f81c: Pulling fs layer
aaf5ad2e1aa3: Pulling fs layer
05ba4d604a56: Pulling fs layer
error pulling image configuration: received unexpected HTTP status: 503 Service Temporarily Unavailable
make[1]: *** [10] Error 1
make[1]: Leaving directory `/tmp/daily_scl_tests/s2i-nodejs-container'
make: *** [build-serial] Error 2
```

### PR DESCRIPTION
**Pull request by phracek**
[EDITED] This commit fixes an error in case of e.g. Fedora registry is not
accessible for a temporary reasons like HTTP 503.
Second pulling should work usually.

In case `FROM scratch` is used in Dockerfile then it is skipped.
In case `FROM ubi8 as ubi-base` is used in Dockerfile the `ubi8` is pulled.

Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

### CODE REVIEW

**Comment by phracek** [comment]
See error like here: https://ci.centos.org/job/SCLo-container-python-rh-fedora/282/

**Comment by phracek** [comment]
I have tested this pulling function on `s2i-base-container` and output seems to be fine:

```bash
s2i-base-container$ make test TARGET=fedora
Makefile:15: warning: overriding recipe for target 'core'
common/common.mk:81: warning: ignoring old recipe for target 'core'
make[1]: Entering directory '/vagrant/s2i-base-container'
Makefile:15: warning: overriding recipe for target 'core'
common/common.mk:81: warning: ignoring old recipe for target 'core'
VERSIONS="core" SKIP_SQUASH=1 UPDATE_BASE= OS=fedora CLEAN_AFTER= DOCKER_BUILD_CONTEXT=. OPENSHIFT_NAMESPACES="" CUSTOM_REPO="" /usr/bin/env bash common/build.sh
-> Version core: building image from 'Dockerfile.fedora' ...
-> Pulling image registry.fedoraproject.org/fedora:31 before building image from Dockerfile.fedora.
Trying to pull repository registry.fedoraproject.org/fedora ...
sha256:60cd711615e0983c533420634ba530283c14a26d875ab310964e2a5666ba957f: Pulling from registry.fedoraproject.org/fedora
c28ace6b0c4a: Retrying in 1 second

```

**Comment by phracek** [comment]
[test]

File: build.sh [hunk 1]
```diff
@@ -76,6 +76,42 @@ function clean_image {
...
+    image_name=$(echo "$line" | cut -d ' ' -f2)
+    # In case FROM scratch is defined, skip it
+    if grep -q "scratch" <<< "$image_name"; then
+        continue
+    fi
+    # In case FROM ubi8 as ubi-base is mentioned
+    # pull ubi8 image
+    if grep -q " as " <<< "$line"; then
+        image_name=$(echo "$line" | cut -d ' ' -f2)
+    fi
```
Comment (pkubatrh) [inline build.sh:98]: I do not see a difference to `image_name=$(echo "$line" | cut -d ' ' -f2)` command slightlz above this part.

File: build.sh [hunk 2]
```diff
@@ -76,6 +76,42 @@ function clean_image {
...
+    echo "-> Pulling image $image_name before building image from $dockerfile."
+    # Sometimes in Fedora case it fails with HTTP 50X
+    # Check if the image is available locally and try to pull it if it is not
+    if docker images "$image_name" &>/dev/null; then
```
Comment (pkubatrh) [inline build.sh:102]: Trying this out for an image that does not exist, the docker/podman command exits with return value 0 either way.

File: build.sh (hunk 1 above)
Comment (phracek) [reply build.sh:98]: Good catch, It seems, like I was trying to get third argument, but second is right. I will remote it.

File: build.sh (hunk 2 above)
Comment (phracek) [reply build.sh:102]: Some example is here: https://github.com/VonC/b2d/blob/2d671bbe1311b63b24e7b8b495e3055dc5c5f97b/apache/build#L6-L8

Comment (pkubatrh) [reply build.sh]: Yes, that would work. Thanks!

File: build.sh [hunk 3]
```diff
@@ -76,6 +76,38 @@ function clean_image {
...
+  local dockerfile="$1"
+
+  # Get image_name from Dockerfile before pulling.
+  while read -r line; do
+    if ! grep -q "^FROM" <<< "$line"; then
+      continue
+    fi
+
+    # In case FROM scratch is defined, skip it
+    if grep -q "scratch" <<< "$image_name"; then
```
Comment (pkubatrh) [inline build.sh:90]: Just a nitpick, please check that the image name is exactly `scratch`, a correct image could in theory have scratch in its name.

Comment (pkubatrh) [reply build.sh:90]: Also, the assignment to `image_name` should be before this line

Comment (phracek) [reply build.sh]: Addressed.

**Comment by phracek** [comment]
[test]

**Comment by pkubatrh** [comment]
lgtm now, thanks!
